### ISSUE TITLE
Issues with Userforms Module

### ISSUE THREAD

**Issue by nishad** [silverstripe/silverstripe-staticpublishqueue#10]
After generating the cache, if I visit any userform enabled page, on submission I'm getting this error page

```
There seems to have been a technical problem. Please click the back button, refresh your browser, and try again.
```

**Comment by barry-bookinglive** [comment]
Hi All,

Just a note to say that I've created a pull request that might be appropriate - it adds a call to a method "canCache" (if it exists) and if this exists it can determine if to cache or not.  This was added to exclude pages based on their accessibility - e.g. if restricted to a logged in user then do not cache.

This would mean each module controls whether it is cacheable instead of putting the focus on this module knowing about all others.  And also provides more fine graded customisation of whether to cache a page - not just based on it's class name.

**Comment by jyrkij** [comment]
@barry-bookinglive Your solution sounds nice!

**Comment by mediabeastnz** [comment]
Did this ever get merged?

**Comment by barry-bookinglive** [comment]
I don't think so, obviously we are using our fork, if you wish to speed this up I'd contact the module owner

**Comment by quinnmerio** [comment]
Running through this thread - not entirely clear if it is possible or not yet to exclude a class/page-type from cache?  yes, no? via yml or a var like: public $excludeFromCache = true;

please advise :-)

**Comment by barry-bookinglive** [comment]
@quinnmerio this is now being discussed on the static cache module instead and is blocked as it requires unit tests which are very hard to create for this... it might end up only being on a branch at this rate

**Comment by dhensby** [comment]
This is fixed now with the uses of `lazy_form_recognition` config (see #121 )
