### ISSUE TITLE
Stable release for SilverStripe 4

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-staticpublishqueue#110]
# Stable release for SilverStripe 4

This module doesn't have a stable released version compatible with SilverStripe 4. The code on master branch is already upgraded to be SS4 compatible so we are not far away from making a release.

It would be nice to get it done as it's been already almost a year since the last release.

**Comment by mfendeksilverstripe** [comment]
^ @chillu

**Comment by chillu** [comment]
Generally agree, this is module which should be used more widely, and one way to achieve that is frequent releases. There's a [4.0.0-beta1](https://github.com/silverstripe/silverstripe-staticpublishqueue/releases) from back in April 2018. In our common interpretation of "beta", that would mean API stable. Since then, there's been [36 commits](https://github.com/silverstripe/silverstripe-staticpublishqueue/compare/4.0.0-beta.1...master).

Are you running this version of the module plus your open pull requests in production without any further modifications? I'm just trying to determine how "stable" the module actually is, which is ideally proven by production use. If in doubt, we could just tag a beta2?

For a stable release, ideally we'd have a rough upgrade guide. Keen to contribute there?

**Comment by mfendeksilverstripe** [comment]
@chillu 

We've been running `dev-master` on one of our big projects for almost 2 years now. The latest commit we have on PROD is `513f660c0e6ff3a2492fd0dceb4e3bd63c7a4f58` (from master branch). I would say it's pretty stable given the scale of this feature is being used on the project.

I'm happy to help if there is something I can do :).

**Comment by chillu** [comment]
I've updated the test suite to the latest dist and latest PHP versions, hopefully that fixes it (passes locally): https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/111.

**Comment by dhensby** [comment]
both v4 and v5 have been released now.
