### ISSUE TITLE
RedirectorPages using 'Another website' (external link) option should be excluded in GenerateStaticCacheJob

### ISSUE THREAD

**Issue by pjayme** [silverstripe/silverstripe-staticpublishqueue#158]
When the 'Another website' option is used on a `RedirectorPage` the `GenerateStaticCacheJob` recognises this as a page to be cached when we think it should be fully excluded as it is not associated with the site. 

This results in a fully broken `GenerateStaticCacheJob` as it is unable to resolve an external url, slowing down the entire process and in some cases halting it completely.

## Acceptance criteria
- When a redirector page pointing to an external site is cached, it naively caches the redirect
- The behaviour for redirects to internal pages stays the same.

**Comment by michalkleiner** [comment]
@pjayme have you tried with the [latest 5.3.0](https://github.com/silverstripe/silverstripe-staticpublishqueue/releases/tag/5.3.0) that was released 9 hours ago and should be addressing the redirector page caching?

**Comment by emteknetnz** [comment]
Different issue to what was fixed, pjayme has already messaged me saying this was an issue after testing the 5.3.0 release.

The other issue was internal links because RedirectoPage::Link() returns the target page url rather that the url of the RedirectoPage.

This issue is external links - I haven't investigated at all but I suspect the staticpublish queue module is making an HTTP request to a separate website when it shouldn't attempt to

**Comment by emteknetnz** [comment]
Different issue to what was fixed, pjayme has already messaged me saying this was an issue after testing the 5.3.0 release.

The other issue was internal links because RedirectoPage::Link() returns the target page url rather that the url of the RedirectoPage.

This issue is external links - I haven't investigated at all but I suspect the staticpublish queue module is making an HTTP request to a separate website when it shouldn't attempt to

**Comment by michalkleiner** [comment]
Fair enough. How do we determine if a domain is local or remote? Sites may have multiple domains assigned to them with or without a proper redirect between them, and domains different to the one that Director::host returns may still be local and valid. It's a less likely use case for redirector pages but can't be completely ruled out.

**Comment by emteknetnz** [comment]
Seems like in that case you should be using an internal redirect then?

Regardless, I suspect the solution here will be to just use the "static redirect template" instead of the "static page template" and not attempt to make any HTTP request from the server when the "Another website" option is selected

**Comment by GuySartorelli** [comment]
Yeah, I agree with Steve. The behaviour really shouldn't matter whether it's an external redirect or not - the redirect response and location should be what's cached which shouldn't require this module to make a request to the target redirect URL at all.

**Comment by emteknetnz** [comment]
>> that's what the change in 5.3.0 was achieving

It did, but only for redirector pages pointing to an internal link

**Comment by emteknetnz** [comment]
I've tested it locally and things seem fine to me, the current behavior of caching 301 redirects to external pages defined in RedirectorPage's seems correct to me, I'd prefer not to change this.

On my local using 5.3.0 and a silverstripe/installer 4.13, I created a RedirectorPage linked to an external site and run the job queue.

I debugged the code and it you'll end up in RedirectorPageController::index() && RedirectorPage::redirectionLink() where a 301 is returned. Then FilesystemPublisher::publishURL() will take the 301 and call FilesystemPublisher::publishRedirect() which creates the html/php files

As far as I can tell there isn't actually an external HTTP request made.

Since things seems to be working correctly I'll mark this one as closed. If someone can show that there is actually a problem here then ping me on this issue and I'll reopen it
