### ISSUE TITLE
TODO: Add subsites integration

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-staticpublishqueue#175]
## Description
There have been numerous discussions regarding Subsites integration, but there are not any PR indicating that this integration has been completed. 
See: https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/70 

If we integrate Subsites, we should set `Subsite::disable_subsite_filter` to `true` in`StaticCacheFullBuildJob::getAllLivePageURLs()`.

**Comment by GuySartorelli** [comment]
Gonna close this since there's no other open issues related to subsites integration - Either it's working, or it's not and nobody really cares.

There's an extension hook right in that spot anyway, so arguably it would be better for a 3rd party module (or subsites itself) to implement an extension to disable the subsite filter at that point, rather than having this module be coupled to subsites.
