### ISSUE TITLE
Deal with URL changes (renames)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-staticpublishqueue#59]
Currently moving a page to a different tree node, or renaming its URLSegment won't remove the old file. @edlinklater has some code for this in a client project.

**Comment by sunnysideup** [comment]
To me this is a significant security risk.  

If you run a static publishing on a site.  The content editor publishes something by accident then changes / removes the page (for obvious reasons), the static HTML file with the sensitive content will sit there forever.  Is it as crude as I describe it here or am I missing something?

I added the following to my code:
```


    public static function remove_cached_content()
    {
        $dir = Director::baseFolder().'/public/cache';
        if (file_exists($dir)) {
            $it = new RecursiveDirectoryIterator($dir, RecursiveDirectoryIterator::SKIP_DOTS);
            $files = new RecursiveIteratorIterator($it, RecursiveIteratorIterator::CHILD_FIRST);
            foreach ($files as $file) {
                if ($file->isDir()) {
                    rmdir($file->getRealPath());
                } else {
                    unlink($file->getRealPath());
                }
            }
            //we do not need to remove the dir itself... 
            //rmdir($dir);
        

```
(UNTESTED)

Whenever you do a full rebuild / a cache delete - why not just wipe the whole lot rather than going through the list as shown here:

https://github.com/silverstripe/silverstripe-staticpublishqueue/blob/master/src/Job/DeleteStaticCacheJob.php#L31-L41

Where does that list of publishedURLs come from and how can we be sure it contains "ALL"?

**Comment by dhensby** [comment]
Hmm - I think this is fixed in the latest version for SS4.

I believe we wrote a task that would "unpublish" the old url and then "publish" the new one. Has anyone tested this in the latest version?

**Comment by dhensby** [comment]
@sunnysideup that task is `Remove a set of static pages from the cache`, so it goes off of a list of URLs to delete.

The "full build job" which republishes all URLs works off of the currently published URLs supplied by the publisher (https://github.com/silverstripe/silverstripe-staticpublishqueue/blob/master/src/Publisher/FilesystemPublisher.php#L207-L230).

In the publishing engine (https://github.com/silverstripe/silverstripe-staticpublishqueue/blob/master/src/Extension/Engine/SiteTreePublishingEngine.php#L77-L98) we detect changes in URLSegment and queue and unpublish and a publish.

**Comment by dhensby** [comment]
I'm closing this as fixed

**Comment by sunnysideup** [comment]
Thank you for looking at this. This definitely seems fixed.
