### ISSUE TITLE
Feature:  Always republish the home page

### ISSUE THREAD

**Issue by DorsetDigital** [silverstripe/silverstripe-staticpublishqueue#84]
Before I dive into a PR for this, I'd like some opinion.
I've got a couple of cases where a site has a 'latest posts' feed on the home page.  This pulls content from the blog module.   Trouble is, when a new post is added, the home page feed isn't automatically updated.

I was thinking that a config option to always rebuild the home page could be useful.  It would be added to the SiteTree publisher, so when any page was updated, the home page cache was also refreshed.   (Disabled by default).  

Can anyone think of major issues, clever features, etc. for this?

**Comment by dhensby** [comment]
I think there are a lot of common dependencies we could infer for most sites around what should be published whenever a page changes...

The problem I see is "where do we stop?"... We can make arguments for why all root level pages should be republished on every change or all parent pages... but this is a bit of an overly opinionated step to take. Just because your homepage references "latest posts" doesn't mean that everyone's does and my preference is to leave this customisable by each site developer.

Is it a lot more work to add the home page to your Page.php declaration of `pagesToCache` (or whatever the method name is)?

Over adding a single purpose config options, I would like some kind of intuitive easily applied way of saying "these are pages that must always be published no matter what"; but I fear that's basically as above, customise the `pagesToCache` on Page.php...

**Comment by DorsetDigital** [comment]
My reason for singling out the home page in particular is that it seems to be quite a common use-case, at least on sites I've built.   In other sections (blog lists, etc.) the publisher already deals with the parent, but due to the decoupling of the home page, I've run into issues.

My preference is also to leave it up to the developer, which is why I suggested an opt-in for the functionality.  

If there's a simple way to do it via the `urlsToCache()` method, then great, but I wasn't sure if that meant all the logic which currently exists in the publisher classes needed to be reproduced in order not to break things... if so, then it's not just a simple task.
